CREATE DATABASE burgers_db;
CREATE TABLE IF NOT EXISTS `burgers_db`.`burgers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `burger_name` VARCHAR(30) NULL DEFAULT NULL,
  `devoured` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci